features:
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
  logo: true
  name: true
  node_user_picture: 1
  slogan: true
facebook_url: 'https://www.facebook.com/simpleinformation/'
twitter_url: 'https://www.simpleinformation.com'
google_plus_url: 'https://www.simpleinformation.com'
linkedin_url: 'https://www.simpleinformation.com'
pinterest_url: 'https://www.simpleinformation.com'
rss_url: ''
show_social_icon: 1
show_credit_link: 1
show_slideshow: 1
no_of_slides: '3'
slide_title_1: 'We''re Rock''n the Baltimore food scene'
slide_description_1: 'Out of the gate, and red hot, come by for some of the city''s most progressive food and fine wines. '
slide_url_1: '#'
slide_image_path_1: /images/slider/slide_01.jpg
slide_title_2: 'Sit outside across from Patterson Park'
slide_description_2: 'Nothing beats a slow dinner on a cool summer night at Patterson Park. '
slide_url_2: '#'
slide_image_path_2: /images/slider/slide_02.jpg
slide_title_3: 'Drupal Design & Development'
slide_description_3: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since'
slide_url_3: '#'
slide_image_path_3: /images/slider/slide_03.jpg
_core:
  default_config_hash: KaLNVgq6qGhSV-TerDCQAiCaPJrmq41RgHhVcYzbxjI
logo:
  use_default: 1
favicon:
  use_default: 1
slide_image_path1: {  }
slide_image_path2: {  }
slide_image_path3: {  }
